name = "Dashboard App Template"
description = "A template for a simple dashboard app in Panel using the Perspective module."
port = 5006
cover_image = "app_cover.jpg"
exclude = [ "*venv", "venv*", ".git", ".env" ]

[python]
library = "panel"
app_file = "app.py"
requirements_file = "requirements.txt"
version = "3.12"

[deploy]
app = "dashboard-app-template"
organization = "test12-jyv8c1f2"